/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-10T16:07:51.090087
 */
package bio.ferlab.datalake.spark3.testmodels.normalized




case class NormalizedClinvarVep(`chromosome`: String = "1",
                                `start`: Long = 63411317,
                                `end`: Long = 63411318,
                                `reference`: String = "G",
                                `alternate`: String = "A",
                                `name`: String = "rs200676709",
                                `clin_sig`: Seq[String] = Seq("Likely_benign"),
                                `consequences`: Seq[String] = Seq("missense_variant"),
                                `biotype`: String = "protein_coding",
                                `impact`: String = "MODERATE",
                                `symbol`: String = "ALG6",
                                `ensembl_gene_id`: String = "ENSG00000088035",
                                `ensembl_transcript_id`: String = "ENST00000263440",
                                `hgvsp`: String = "ENSP00000263440.5:p.Gly222Asp",
                                `hgvsc`: String = "ENST00000263440.6:c.665G>A",
                                `hgvsg`: String = "1:g.63411316G>A")

