/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-09-06T12:59:45.198688
 */
package bio.ferlab.datalake.testutils.models.normalized




case class NormalizedCosmicMutationSet(`chromosome`: String = "2",
                                       `start`: Long = 197402110,
                                       `end`: Long = 197402110,
                                       `reference`: String = "T",
                                       `alternate`: String = "C",
                                       `mutation_url`: String = "https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=29491889&genome=37",
                                       `shared_aa`: Int = 9,
                                       `genomic_mutation_id`: String = "COSV59205318",
                                       `cosmic_sample_mutated`: Int = 699,
                                       `cosmic_sample_tested`: Int = 86821,
                                       `dnds_disease_qval_sig`: Seq[String] = Seq("breast=4.73e-24"),
                                       `mutation_significance_tier`: String = "2",
                                       `onc_tsg`: Seq[String] = Seq("oncogene"),
                                       `cgc_tier`: Int = 1,
                                       `gene_name`: String = "SF3B1",
                                       `accession_number`: String = "ENST00000335508.6",
                                       `legacy_mutation_id`: String = "COSM84677",
                                       `mutation_cds`: String = "c.2098A>G",
                                       `mutation_aa`: String = "p.K700E",
                                       `disease`: Seq[String] = Seq("NS/NS/NS=17/111=15.32%", "breast/carcinoma/ductal_carcinoma=38/2525=1.5%", "haematopoietic_and_lymphoid_tissue/haematopoietic_neoplasm/chronic_myelomonocytic_leukaemia=10/861=1.16%", "haematopoietic_and_lymphoid_tissue/haematopoietic_neoplasm/essential_thrombocythaemia=8/542=1.48%", "haematopoietic_and_lymphoid_tissue/haematopoietic_neoplasm/myelodysplastic_syndrome=252/4629=5.44%", "haematopoietic_and_lymphoid_tissue/haematopoietic_neoplasm/myelofibrosis=12/1077=1.11%", "haematopoietic_and_lymphoid_tissue/lymphoid_neoplasm/"),
                                       `wgs_disease`: Seq[String] = Seq("haematopoietic_and_lymphoid_tissue/lymphoid_neoplasm/B_cell_prolymphocytic_leukaemia=6/32=18.75%", "haematopoietic_and_lymphoid_tissue/haematopoietic_neoplasm/myelodysplastic_syndrome=7/106=6.6%", "haematopoietic_and_lymphoid_tissue/lymphoid_neoplasm/chronic_lymphocytic_leukaemia-small_lymphocytic_lymphoma=60/1242=4.83%", "breast/carcinoma/ductal_carcinoma=12/652=1.84%"),
                                       `aa_mut_start`: Int = 700,
                                       `aa_mut_stop`: Int = 700,
                                       `aa_wt_allele_seq`: String = "K",
                                       `aa_mut_allele_seq`: String = "E",
                                       `mutation_description_cds`: String = "Substitution",
                                       `mutation_description_aa`: String = "Substitution - Missense",
                                       `ontology_mutation_code`: String = "SO:0001583")

