/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-02-15T16:13:44.624
 */
package bio.ferlab.datalake.testutils.models.genomicimplicits

case class Genotype(calls: Array[Int])
