/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-02-02T08:07:29.806
 */
package bio.ferlab.datalake.spark3.testmodels


case class OrphanetGeneSetOutput(orpha_code: Long = 166024,
                                 disorder_id: Long = 17601,
                                 expert_link: String = "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024",
                                 name: String = "Multiple epiphyseal dysplasia, Al-Gazali type",
                                 disorder_type_id: Long = 21394,
                                 disorder_type_name: String = "Disease",
                                 disorder_group_id: Long = 36547,
                                 disorder_group_name: String = "Disorder",
                                 gene_source_of_validation: String = "22587682[PMID]",
                                 gene_id: Long = 20160,
                                 gene_symbol: String = "KIF7",
                                 gene_name: String = "kinesin family member 7",
                                 gene_synonym_list: List[String] = List("JBTS12"),
                                 ensembl_gene_id: String = "ENSG00000166813",
                                 genatlas_gene_id: String = "KIF7",
                                 HGNC_gene_id: String = "30497",
                                 omim_gene_id: String = "611254",
                                 reactome_gene_id: String = "Q2M1P5",
                                 swiss_prot_gene_id: String = "Q2M1P5",
                                 association_type: String = "Disease-causing germline mutation(s) in",
                                 association_type_id: Long = 17949,
                                 association_status: String = "Assessed",
                                 gene_locus_id: Long = 16859,
                                 gene_locus: String = "15q26.1",
                                 gene_locus_key: Long = 1,
                                 average_age_of_onset: List[String] = List("Infancy", "Neonatal"),
                                 average_age_of_death: List[String] = List(),
                                 type_of_inheritance: List[String] = List("Autosomal recessive"))



