/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2022-12-21T12:33:30.559008
 */
package bio.ferlab.datalake.spark3.testmodels


case class SpliceAiOutput(`chromosome`: String = "2",
                          `start`: Long = 210862942,
                          `end`: Long = 210862946,
                          `reference`: String = "GGCA",
                          `alternate`: String = "G",
                          `allele`: String = "G",
                          `symbol`: String = "KCNH1",
                          `ds_ag`: String = "0.00",
                          `ds_al`: String = "0.00",
                          `ds_dg`: String = "0.00",
                          `ds_dl`: String = "0.00",
                          `dp_ag`: String = "-3",
                          `dp_al`: String = "36",
                          `dp_dg`: String = "32",
                          `dp_dl`: String = "22")

