/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2022-02-07T15:08:30.079524
 */
package bio.ferlab.datalake.spark3.utils

import java.sql.Timestamp


case class TestClassOutput(`a`: String = "a",
                           `b`: Long = 0,
                           `c`: String = "{\"c\":1, \"d\":2}",
                           `d`: List[String] = List(),
                           `e`: Timestamp = java.sql.Timestamp.valueOf("1900-01-01 00:00:00.0"),
                           `f`: Array[Byte] = Array(0.toByte, 2.toByte))

