/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2023-06-16T10:00:09.313196
 */
package bio.ferlab.datalake.spark3.testmodels.normalized




case class NormalizedCosmic(`chromosome`: String = "10",
                            `start`: Long = 43077027,
                            `symbol`: String = "RET",
                            `name`: String = "ret proto-oncogene",
                            `cosmic_gene_id`: String = "COSG68325",
                            `tier`: Int = 1,
                            `chr_band`: String = "11.21",
                            `somatic`: Boolean = true,
                            `germline`: Boolean = true,
                            `tumour_types_somatic`: Set[String] = Set("medullary thyroid", "papillary thyroid", "pheochromocytoma", "NSCLC", "Spitzoid tumour"),
                            `tumour_types_germline`: Set[String] = Set("medullary thyroid", "papillary thyroid", "pheochromocytoma"),
                            `cancer_syndrome`: String = "multiple endocrine neoplasia 2A/2B",
                            `tissue_type`: Seq[String] = Seq("E", "O"),
                            `molecular_genetics`: String = "Dom",
                            `role_in_cancer`: Set[String] = Set("oncogene", "fusion"),
                            `mutation_types`: Set[String] = Set("T", "Mis", "N", "F"),
                            `translocation_partner`: Set[String] = Set("H4", "PRKAR1A", "NCOA4", "PCM1", "GOLGA5", "TRIM33", "KTN1", "TRIM27", "HOOK3", "KIF5B", "CCDC6"),
                            `other_germline_mutation`: Boolean = true,
                            `other_syndrome`: Set[String] = Set("Hirschsprung disease"),
                            `synonyms`: Set[String] = Set("RET", "ENSG00000165731.18", "P07949", "5979", "CDHF12", "CDHR16", "PTC", "RET51"))

