/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-29T20:20:03.178767
 */
package bio.ferlab.datalake.testutils.models.raw


case class RawCosmicGeneSet(`Gene Symbol`: String = "RET",
                            `Name`: String = "ret proto-oncogene",
                            `Entrez GeneId`: String = "5979",
                            `Genome Location`: String = "10:43077027-43130351",
                            `Tier`: String = "1",
                            `Hallmark`: String = "Yes",
                            `Chr Band`: String = "11.21",
                            `Somatic`: String = "yes",
                            `Germline`: String = "yes",
                            `Tumour Types(Somatic)`: String = "medullary thyroid, papillary thyroid, pheochromocytoma, NSCLC, Spitzoid tumour",
                            `Tumour Types(Germline)`: String = "medullary thyroid,  papillary thyroid, pheochromocytoma",
                            `Cancer Syndrome`: String = "multiple endocrine neoplasia 2A/2B",
                            `Tissue Type`: String = "E, O",
                            `Molecular Genetics`: String = "Dom",
                            `Role in Cancer`: String = "oncogene, fusion",
                            `Mutation Types`: String = "T, Mis, N, F",
                            `Translocation Partner`: String = "H4, PRKAR1A, NCOA4, PCM1, GOLGA5, TRIM33, KTN1, TRIM27, HOOK3, KIF5B, CCDC6",
                            `Other Germline Mut`: String = "yes  ",
                            `Other Syndrome`: String = "Hirschsprung disease",
                            `COSMIC ID`: String = "COSG206185",
                            `cosmic gene name`: String = "RET",
                            `Synonyms`: String = "5979,CDHF12,CDHR16,ENSG00000165731.18,HSCR1,MEN2A,MEN2B,MTC1,P07949,PTC,RET,RET51")