/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-29T20:20:03.178767
 */
package bio.ferlab.datalake.testutils.models.raw


case class RawCosmicGeneSet(`GENE_SYMBOL`: String = "RET",
                            `NAME`: String = "ret proto-oncogene",
                            `COSMIC_GENE_ID`: String = "COSG68325",
                            `CHROMOSOME`: String = "10",
                            `GENOME_START`: String = "43077027",
                            `GENOME_STOP`: String = "43130351",
                            `CHR_BAND`: String = "11.21",
                            `SOMATIC`: String = "y",
                            `GERMLINE`: String = "y",
                            `TUMOUR_TYPES_SOMATIC`: String = "medullary thyroid, papillary thyroid, pheochromocytoma, NSCLC, Spitzoid tumour",
                            `TUMOUR_TYPES_GERMLINE`: String = "medullary thyroid,  papillary thyroid, pheochromocytoma",
                            `CANCER_SYNDROME`: String = "multiple endocrine neoplasia 2A/2B",
                            `TISSUE_TYPE`: String = "E, O",
                            `MOLECULAR_GENETICS`: String = "Dom",
                            `ROLE_IN_CANCER`: String = "oncogene, fusion",
                            `MUTATION_TYPES`: String = "T, Mis, N, F",
                            `TRANSLOCATION_PARTNER`: String = "H4, PRKAR1A, NCOA4, PCM1, GOLGA5, TRIM33, KTN1, TRIM27, HOOK3, KIF5B, CCDC6",
                            `OTHER_GERMLINE_MUT`: String = "y",
                            `OTHER_SYNDROME`: String = "Hirschsprung disease",
                            `TIER`: String = "1",
                            `SYNONYMS`: String = "RET,ENSG00000165731.18,P07949,5979,CDHF12,CDHR16,PTC,RET51")