/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-29T20:20:03.178767
 */
package bio.ferlab.datalake.testutils.models.raw

case class RawDDDGeneSet(
                          `g2p id`: String = "G2P00001",
                          `gene symbol`: String = "HMX1",
                          `gene mim`: String = "142992",
                          `hgnc id`: String = "5017",
                          `previous gene symbols`: String = "H6; NKX5-3",
                          `disease name`: String = "OCULOAURICULAR SYNDROME",
                          `disease mim`: String = "612109",
                          `disease MONDO`: Option[String] = None,
                          `allelic requirement`: String = "biallelic_autosomal",
                          `cross cutting modifier`: Option[String] = None,
                          `confidence`: String = "probable",
                          `variant consequence`: String = "loss of function",
                          `variant types`: String = "missense_variant; inframe_deletion; inframe_insertion",
                          `molecular mechanism`: String = "loss of function",
                          `molecular mechanism categorisation`: String = "inferred",
                          `molecular mechanism evidence`: Option[String] = None,
                          `phenotypes`: String = "HP:0000007; HP:0000482; HP:0000647; HP:0007906; HP:0000568; HP:0000589; HP:0000639; HP:0000518; HP:0001104",
                          `publications`: String = "18423520; 25574057; 29140751",
                          `panel`: String = "DD",
                          `comments`: Option[String] = None,
                          `date of last review`: String = "2019-09-26 16:23:46+00:00"
                        )