/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2023-06-25T14:17:43.809428
 */
package bio.ferlab.datalake.spark3.testmodels.prepared




case class PreparedGeneSuggestions(`type`: String = "gene",
                                   `symbol`: String = "OR4F5",
                                   `suggestion_id`: String = "9b8016c31b93a7504a8314ce3d060792f67ca2ad",
                                   `suggest`: Seq[GENE_SUGGEST] = Seq(GENE_SUGGEST(), GENE_SUGGEST(Seq("BII", "CACH6", "CACNL1A6", "Cav2.3", "EIEE69", "gm139", "ENSG00000198216"),3)),
                                   `ensembl_gene_id`: String = "ENSG00000198216")

case class GENE_SUGGEST(`input`: Seq[String] = Seq("OR4F5"),
                        `weight`: Int = 5)
