/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2023-01-12T15:39:09.569886
 */
package bio.ferlab.datalake.spark3.testmodels.enriched




case class EnrichedSpliceAi(`chromosome`: String = "1",
                            `start`: Long = 210862942,
                            `end`: Long = 210862946,
                            `reference`: String = "GGCA",
                            `alternate`: String = "G",
                            `allele`: String = "G",
                            `symbol`: String = "KCNH1",
                            `ds_ag`: Double = 0.0,
                            `ds_al`: Double = 0.0,
                            `ds_dg`: Double = 0.0,
                            `ds_dl`: Double = 0.0,
                            `dp_ag`: Int = -3,
                            `dp_al`: Int = 36,
                            `dp_dg`: Int = 32,
                            `dp_dl`: Int = 22,
                            `max_score`: MAX_SCORE = MAX_SCORE())

case class MAX_SCORE(`ds`: Double = 0.0,
                     `type`: Seq[String] = Seq("AG", "AL", "DG", "DL"))
