name: Deploy to Sonatype

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with sbt
        run: sbt clean package
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2
          username: ${{ secrets.SONATYPE_USER }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          format: maven2
          repository: releases
          coordinates: groupId=bio.ferlab artifactId=datalake-core version=0.0.11
          assets: extension=jar
          filename: ./datalake-core/target/scala-2.12/datalake-core_2.12-0.0.11.jar