name: Publish Artifact

on:
  push:
    tags:
      - v*

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSS_SONATYPE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.OSS_SONATYPE_GPG_PASSPHRASE }}
          git_user_signingkey: false

      - name: Publish Artifact
        uses: sbt/setup-sbt@v1
        shell: bash
        env:
          tag: ${{ github.ref_name }}
          SONATYPE_REALM: ${{ vars.OSS_SONATYPE_REALM }}
          SONATYPE_HOST: ${{ vars.OSS_SONATYPE_HOST }}
          SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        run: |
          export PGP_PASSPHRASE=${{ secrets.OSS_SONATYPE_GPG_PASSPHRASE }}
          # Remove the leading 'v' from the tag string
          export VERSION=${tag#v}
          sbt 'publishSigned; sonatypeRelease'

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
