name: Publish Artifact

on:
  push:
    tags:
      - v*

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'sbt'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: false

      - name: List keys
        run: gpg -K

      - name: Publish Artifact
        shell: bash
        env:
          tag: ${{ github.ref_name }}
        run: |
          mkdir /home/runner/.sbt
          echo "realm=${{ secrets.SONATYPE_REALM }}" >> /home/runner/.sbt/sonatype_credentials
          echo "host=${{ secrets.SONATYPE_HOST }}" >> /home/runner/.sbt/sonatype_credentials
          echo "user=${{ secrets.SONATYPE_USERNAME }}" >> /home/runner/.sbt/sonatype_credentials
          echo "password=${{ secrets.SONATYPE_PASSWORD }}" >> /home/runner/.sbt/sonatype_credentials
          export PGP_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}
          # Remove the leading 'v' from the tag string
          export version=${tag#v}
          sbt 'set version := "version"; publishSigned; sonatypeRelease'

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes          
